---
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z-cpuv1
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: "iman"
      MINIO_ROOT_PASSWORD: "j80K3878rgUc346EgqYZ1GSMkNX2LW"
    command: server /data --console-address ":9001"
